name: deploy
on: push
env:
  ghuser: nqthqn
  dhuser: nqthqn1
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        fork:
          - "for-test"
    steps:
      - name: get fork
        id: forky
        uses: actions/checkout@v4
        with:
          repository: "${{ env.ghuser }}/${{ matrix.fork }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          fetch-tags: true

      - name: debug
        run: ${{ toJson(steps.forky.outputs) }} # TODO: get all the tags


      # - name: dockerhub login
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: dockhub tags
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ env.dhuser }}/${{ matrix.fork }}
      #     tags: |
      #       type=semver,pattern={{version}}

      # - name: docker build & push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     tags: ${{ steps.meta.outputs.tags }} # TODO: find the latest tag, v3
      #     labels: ${{ steps.meta.outputs.labels }}
