name: deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get fork
        id: forky
        uses: actions/checkout@v4
        with:
          repository: nqthqn/for-test
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          fetch-tags: true

      - name: dockerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: dockhub tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nqthqn1/for-test
          tags: |
            type=semver,pattern={{version}}

      - name: docker build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
