name: deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - "for-test"
    steps:
      - name: get fork
        uses: actions/checkout@v4
        with:
          repository: nqthqn/${{ matrix.repo }}
          path: ${{ matrix.fork }}
          fetch-depth: 0 # kinda slow

      - name: Fetch tags
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 || echo "none")
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV

      - name: dockerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: docker build & push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.repo }}
          tags: ${{ env.latest_tag }}
