name: Push images from forks

on:
  release:
    types: [published]

jobs:
  echo_dockerfile_from_fork:
    name: Echo Dockerfile from fork
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the triggering repository
        uses: actions/checkout@v4

      - name: Clone the forked repository with Dockerfile
        run: |
          git clone https://github.com/nqthqn/dcc-admin-dashboard.git dcc-admin-dashboard

      - name: Echo Dockerfile
        run: |
          head dcc-admin-dashboard/Dockerfile

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: nqthqn1/helloworld

      - name: Debugging
        id: debug
        run: echo "${{ steps.meta.outputs }}"

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./dcc-admin-dashboard
          file: ./dcc-admin-dashboard/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
