name: "goal: clone fork, check tags, deploy if new"
on: push
jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        fork:
          - "dcc-admin-dashboard"
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nqthqn1/${{ matrix.fork }}

      - run: echo "${{ toJson(steps.meta.outputs) }}"
      - run: echo "${{ toJson(steps.meta) }}"
      - run: echo "${{ toJson(github) }}"

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
