name: "goal: clone fork, check tags, deploy if new"
run-name: YOYOYO ${{ github.sha1 }}
on: push
env:
  ghuser: nqthqn
  dhuser: nqthqn1
jobs:
  build_push_forks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        fork:
          - "for-test"
    steps:
      - name: 1 ------- Get the fork
        uses: actions/checkout@v4
        with:
          repository: "${{ env.ghuser }}/${{ matrix.fork }}"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 2 ------- Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 3 ------ Get tags from DockerHub
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.dhuser }}/${{ matrix.fork }}

      - name: 4 ------ Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
