name: Clone forks and cat Dockerfiles
on: push
env:
  base: https://github.com/${{github.repository_owner}}
jobs:
  haha:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        fork:
          - "dcc-admin-dashboard"
          - "admin-dashboard-claim-page"
    steps:
      - name: Clone the fork
        run: git clone ${{env.base}}/${{matrix.fork}}.git
      - name: Prove it
        run: cat ./${{matrix.fork}}/Dockerfile
