name: Testing matrix
on: push
run-name: For fun

jobs:
  haha:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stuff: ["test", "this"]
    steps:
      - name: See her?
        run: echo '${{ matrix.stuff }}'
